### ISSUE TITLE
Error displayed opening a python notebook

### ISSUE THREAD

**Issue by ederign** [kubeflow-kale/kale#451]
1. Open candies_sharing on v2.0-frontend-dev branch
2. Click on Kale extension
3. Click on Enable

<img width="1682" height="1222" alt="Image" src="https://github.com/user-attachments/assets/654f61a3-1151-4339-a53e-e427367a70bb" />

**Comment by hmtosi** [comment]
@ederign I will work on this issue, will you please assign it to me?

**Comment by jesuino** [comment]
I did change on my installation the method [`scrollToCell` in `NotebookUtils`](https://github.com/kubeflow-kale/kale/blob/v2.0-frontend-dev/labextension/src/lib/NotebookUtils.tsx#L555) to use the object cell instead the cell index and it seems to have fixed this error:

```
notebook.content.scrollToCell(cell.cell);
```

**Comment by jesuino** [comment]
This should be fixed by this PR: https://github.com/kubeflow-kale/kale/pull/470

**Comment by hmtosi** [comment]
I ran JupyterLab with the changes from #470. Opening a notebook does still throw a couple of errors, but not the weakmap warning.

<img width="2547" height="1234" alt="Image" src="https://github.com/user-attachments/assets/d87f99e8-1bcf-4dce-9af1-71c9bc497444" />
<img width="2547" height="1234" alt="Image" src="https://github.com/user-attachments/assets/83f1efad-2038-42be-aaa1-24f4235171b7" />

Once the notebook is opened and I have dismissed those two errors, I am able to "Enable" Kale with no further errors:

<img width="2547" height="1234" alt="Image" src="https://github.com/user-attachments/assets/529c59e1-2b0f-4bde-b781-ea0fec9dd367" />


Shall we close this ticket and open a new one for the other issues, or should we address those here as well?

**Comment by StefanoFioravanzo** [comment]
@hmtosi I think we should keep this issue until we have a mechanism to nicely display any error that occurs when opening a notebook, removing these cryptic errors that are popping up now.
Do you have an idea whey we are still having them?

**Comment by jesuino** [comment]
@StefanoFioravanzo me and @hmtosi  made a local research and the reason is that Kale is registering to listen to all errors that happens on the client and it includes even errors unrelated to Kale

It has a [function to handle general errors](https://github.com/kubeflow-kale/kale/blob/main/labextension/src/lib/RPCUtils.tsx#L23) and it is [registered](https://github.com/kubeflow-kale/kale/blob/main/labextension/src/widget.tsx#L79) for all the errors that happens on the browser session. So errors coming from other extensions force the Dialog to be displayed.

<img width="1911" height="669" alt="Image" src="https://github.com/user-attachments/assets/969e6daa-a7bd-4ebb-87fb-f2d6d4556b0c" />

My suggestion to fix it would be simply remove the dialog and log the error, in another words, uncomment the line that logs the error and remove the [else clause](https://github.com/kubeflow-kale/kale/blob/main/labextension/src/lib/RPCUtils.tsx#L29) .

**Comment by hmtosi** [comment]
I can confirm, I was a bit mislead by the error messages as I assumed they were all related to kale. Uncommenting [this line](https://github.com/kubeflow-kale/kale/blob/main/labextension/src/lib/RPCUtils.tsx#L24) allowed me to see the actual errors in the console, and it was a matter of uninstalling a couple of jupyterlab extension installations which had become flaky. I can now open and close notebooks with no error messages on the UI!

**Comment by hmtosi** [comment]
We propose that to prevent the modal window from blocking a user, we should change to showing the error in a JupyterLab toast so that a user doesn't have to dismiss the error to continue their work. @StefanoFioravanzo @Amrit27k is that alright with you?

**Comment by StefanoFioravanzo** [comment]
Sounds great to me! Congrats for finding the root cause

**Comment by hmtosi** [comment]
I've created the toast, and added some error handling to help clearly identify the root cause within the message! I just opened the PR, and it has some remaining questions. Here is the current appearance of the toast, showing an uncaught error in the `lckr-jupyterlab-variableinspector` extension.

<img width="2553" height="1401" alt="Image" src="https://github.com/user-attachments/assets/bc28491b-dfab-43bd-b575-d3c4b258ec2b" />

**Comment by hmtosi** [comment]
Fixed by #496
